#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("appBusinessFormBuilder.Resource", IsApplication=true)]

namespace appBusinessFormBuilder
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int antiquewhite = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int black = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int cellback = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int indigo = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int transparent = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int white = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CShapedTextBox = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int defaultRectangle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int defaultSpinner = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int defaultSpinner2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int DetailButton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int DetailButtonNormal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int DetailButtonPressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int mycursor = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int NShapedTextBox = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int spinner_default_arrow = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int spinner_default_arrow2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int spinner_default_holo_light_am = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int spinner_default_holo_light_am2 = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int EmptyLayout = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int MainLayout = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int SpinnerListItem = 2131165186;
			
			// aapt resource value: 0x7f07000a
			public const int btnCreateNewForm = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int btnCreateNewForm2 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int btnCreateNewForm4 = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int btnPreferences = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int btnPreferences2 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int fragment_container = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int hfEditStatus = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int tableButtonRow3 = 2131165197;
			
			// aapt resource value: 0x7f070008
			public const int tableHomeLayout = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int tableRow1 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int tableRow2 = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060004
			public const int CellColumnId = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int CellId = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int CellRowId = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int CellSectionId = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int CellType = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int FormId = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int ParameterId = 2131099649;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layoutEmpty = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layoutSpinner = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int layoutSpinnerBase = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int layoutZoom = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int textarea = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int textbox = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int CellReference = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
